---
# Task File for Pythia

- name: Setting Ansible Remote Temporary Directory
  set_fact:
    ansible_remote_tmp: "{{ remote_stage_directory }}"
  tags:
    - client

###################################################################################
# Check which Mountpoint is used for the specified Oracle Home
# Tag: client
###################################################################################
- name: Check which mountpoint is used by {{ client[client_version|string].oracle_home }}
  command: findmnt -n -o TARGET --target {{ client[client_version|string].oracle_home }}
  become: yes
  register: oracle_home_mount
  tags:
    - client

###################################################################################
# Check for enough Disk Space for new Oracle Home. Has to run twice because
# overloaded Variable space_needed_gb is defined on Playbook call.
# Tag: client
###################################################################################
- name: Check for enough available diskspace for {{ client[client_version|string].oracle_home }}
  assert:
    that: item.size_available > ({{ space_needed_gb }}* 1024 * 1024 * 1024)
    fail_msg: There should be at least {{ space_needed_gb }}GB of free space for installing Client Software
    success_msg: There is sufficient space for installing Client Software
  become: yes
  when: (item.mount == oracle_home_mount.stdout) and (space_needed_gb > 0)
  with_items:
    - "{{ ansible_mounts }}"
  loop_control:
    label: "{{ item.mount }}"
  tags:
    - client

- name: Check for enough available diskspace for {{ client[client_version|string].oracle_home }}
  assert:
    that: item.size_available > (client[client_version|string].space_needed_gb * 1024 * 1024 * 1024)
    fail_msg: There should be at least {{ rdbms[oracle_version|string].space_needed_gb }}GB of free space for installing Client Software
    success_msg: There is sufficient space for installing Client Software
  become: yes
  when: (item.mount == oracle_home_mount.stdout) and (space_needed_gb <= 0)
  with_items:
    - "{{ ansible_mounts }}"
  loop_control:
    label: "{{ item.mount }}"
  tags:
    - client

###################################################################################
# Check if the specified Oracle Home is already installed / registered within the
# Oracle Inventory and if the specified Oracle Home is empty or not.
# Tag: client
###################################################################################
- name: Check if Oracle Home specified already registered in Inventory
  shell: "grep -w {{ client[client_version|string].oracle_home }} {{ client[client_version|string].oracle_inventory }}/ContentsXML/inventory.xml"
  become: yes
  register: result
  failed_when: "'ERROR' in result.stderr"
  tags:
    - client

- name: Oracle Home {{ client[client_version|string].oracle_home }} already registered in Inventory
  assert:
    that: client[client_version|string].oracle_home not in item.stdout
    fail_msg: "The Oracle Home {{ client[client_version|string].oracle_home }} already registered in Inventory"
    success_msg: "Oracle Home {{ client[client_version|string].oracle_home }} not found."
  become: yes
  with_items:
    - "{{ result }}"
  tags:
    - client

- name: Check if Oracle Home specified is empty
  become: yes
  find:
    paths: "{{ client[client_version|string].oracle_home }}"
  register: emptyHome
  tags:
    - client

- name: Oracle Home specified is not empty
  fail:
    msg: "Oracle Home {{ client[client_version|string].oracle_home }} specified is not empty!"
  when: emptyHome.matched > 0
  tags:
    - client

###################################################################################
# Oracle Client is now copied to the Target Server and uncompressed.
# After that, it is installed by runInstaller.
# Tag: client
###################################################################################

- name: Be patient
  debug:
    msg: "The next Step will take several Minutes to complete!"
  tags:
    - client

- name: Copy Oracle Software Archive to Staging Area {{ remote_stage_directory }}
  become: yes
  copy:
    src: "{{ local_stage_directory }}/{{ client[client_version|string].client_dir }}/{{ client[client_version|string].client_file }}"
    dest: "{{ remote_stage_directory }}/{{ client[client_version|string].client_file }}"
    remote_src: no
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
  tags:
    - client

- name: Unpack Oracle Software
  become: yes
  become_user: "{{ oracle_user }}"
  unarchive:
    src: "{{ remote_stage_directory }}/{{ client[client_version|string].client_file }}"
    dest: "{{ remote_stage_directory }}"
    remote_src: yes
    mode: 0755
    group: "{{ oracle_group }}"
    owner: "{{ oracle_user }}"
  tags:
    - client

- name: Cleanup Staging Area
  file:
    path: "{{ remote_stage_directory }}/{{ client[client_version|string].client_file }}"
    state: absent
  become: yes
  become_user: "{{ oracle_user }}"
  tags:
    - client

- name: Setup Oracle Client Software Response File
  become: yes
  become_user: "{{ oracle_user }}"
  template:
    src: roles/pythia/templates/{{ client_version }}_Client.rsp.j2
    dest: "{{ remote_stage_directory }}/client/response/{{ client_version }}_Client.rsp"
    mode: 0755
  tags:
    - client

- name: Install Oracle Client Software
  become: yes
  become_user: "{{ oracle_user }}"
  shell: "{{ remote_stage_directory }}/client/runInstaller -silent -ignoreSysPrereqs -waitforcompletion -responseFile {{ remote_stage_directory }}/client/response/{{ client_version }}_Client.rsp -noconfig"
  register: result
  failed_when: ("ERROR" in result.stdout) or ("FATAL" in result.stdout)
  tags:
    - client

- name: Execute root Skripts
  shell: "{{ item }}"
  become: yes
  register: result
  with_items:
    - "/bin/sh {{ client[client_version|string].oracle_inventory }}/orainstRoot.sh"
    - "/bin/sh {{ client[client_version|string].oracle_home }}/root.sh"
  failed_when: ("ERROR" in result.stdout) or ("FATAL" in result.stdout)
  tags:
    - client

- name: Cleanup Remote Staging Area
  become: yes
  become_user: "{{ oracle_user }}"
  file:
    path: "{{ remote_stage_directory }}/client"
    state: absent
  tags:
    - client