---

###################################################################################
# Find out if the specified Oracle SID is running on the Target Server
# Tag: sqlscript
###################################################################################

- name: Check which Oracle Home is used by {{ oracle_sid }}
  become: true
  shell: "cat /etc/oratab | grep -w {{ oracle_sid }} | awk -F \":\" {'print$2'}"
  args:
    removes: /etc/oratab
  register: home_list
  tags:
    - sqlscript

- name: Oracle SID {{ oracle_sid }} can not be found on the Target Server
  fail:
    msg: "The Oracle SID {{ oracle_sid }} does not exist on the Target System"
  when: (home_list is undefined) or (home_list.stdout_lines|length == 0)
  tags:
    - sqlscript

###################################################################################
# Copy the SQL Scripts under the local SQL Script Stage Directory to the Target
# Server. All copied Scripts are executed on the specified Oracle SID.
# Tag: sqlscript
###################################################################################

- name: Copy Scripts to {{ remote_sql_stage_directory }}
  copy:
    src: "{{ local_sql_stage_directory }}/"
    dest: "{{ remote_sql_stage_directory }}"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
    mode: 0755
  become: true
  become_user: "{{ oracle_user }}"
  tags:
    - sqlscript

- name: Gather Scripts for execution
  become: true
  find:
    paths: "{{ remote_sql_stage_directory }}/"
    file_type: file
  register: script_file_list
  tags:
    - sqlscript

###################################################################################
# Preprocess to ensure that the last line in the SQL Script File is an exit command.
# Otherwise, the Script will hang forever.
# Tag: sqlscript
###################################################################################

- name: Preprocess Scripts for execution
  become: true
  become_user: "{{ oracle_user }}"
  lineinfile:
    path: "{{ item.path }}"
    line: "exit;"
    state: present
    create: true
    mode: 0644
  with_items:
    - "{{ script_file_list.files }}"
  tags:
    - sqlscript

- name: Executing SQL Scripts
  become: true
  become_user: "{{ oracle_user }}"
  shell: "{{ home_list.stdout_lines[0] }}/bin/sqlplus / as sysdba @{{ item.path }}"
  changed_when: "script_output.rc == 0"
  environment:
    ORACLE_HOME: "{{ home_list.stdout_lines[0] }}"
    ORACLE_SID: "{{ oracle_sid }}"
  with_items:
    - "{{ script_file_list.files }}"
  register: script_output
  tags:
    - sqlscript

###################################################################################
# Show the SQL Script Output if the scriptoutput Variable is specified.
# Tag: scriptoutput
###################################################################################

- name: SQL Script Output
  debug:
    msg: "{{ script_output }}"
  when: scriptoutput|bool

###################################################################################
# Cleanup the Scripts from the Remote Staging Area
# Tag: sqlscript
###################################################################################

- name: Cleanup Scripts
  become: true
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ script_file_list.files }}"
  tags:
    - sqlscript
