name: Ansible Lint  # feel free to pick your own name

on: 
  push:
    branches:
      - develop
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v3

    - name: Lint Ansible Playbook
      # replace "master" with any valid ref
      uses: ansible/ansible-lint-action@v4-eol
      with:
        # [required]
        # Paths to ansible files (i.e., playbooks, tasks, handlers etc..)
        # or valid Ansible directories according to the Ansible role
        # directory structure.
        # If you want to lint multiple ansible files, use the following syntax
        # targets: |
        #   playbook_1.yml
        #   playbook_2.yml
        targets: |
          pythia.yml
          roles/pythia/
        override-deps: |
          ansible-lint==5.3.2
        args: "-p -x command-instead-of-shell -x risky-shell-pipe -x no-jinja-when"